version: '3.7'

volumes: 
  work: {}

services:
  nest-web:
    container_name: rest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./rest:/rest
      - work:/work
    command: python main.py