version: '3.7'

volumes: 
  work: {}

services:
  nest-web:
    container_name: nest-web-main
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./rest:/opt/rest
      - ./poetry:/opt/poetry
    command: python main.py