[tool.poetry]
name = "rest"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "==3.7.4"

[tool.poetry.dev-dependencies]
flask = "==1.1.1"
flask-basicauth = "==0.2.0"
flask-restful = "==0.3.7"
pytest = "==5.2.1"
